atom/snippets

lib/snippets.coffee
spec/snippet-loading-spec.coffee

:warning: Depends on atom/atom@a1b4820c044073d2e46d0e2505ae7a1ee7e89272 and atom/atom#4773 being released in v0.166 :warning:

Use new signature for atom.config.get

---

lib/snippets.coffee
spec/snippets-spec.coffee

Currently, if a snippet prefix precedes the cursor, snippet expansion is triggered by the `tab` key. This PR *prevents* triggering snippet expansion if the snippet prefix preceding the cursor is part of a larger word, as defined by the `editor.nonWordCharacters` config setting. 
I'm not sure if this is the right thing to do, but I think it addresses issues raised by @dsandstrom in #59.

Don't trigger expansion when prefix is part of a larger word

---

lib/snippet-body.pegjs
spec/body-parser-spec.coffee

Allow escaped `$` in snippet body to allow strings that look like a tabstop.
E.g. output `\$1` as `$1`, not as `\` + tabstop
PS: I was unable to run Jasmine specs because of `Module did not self-register` error, but I tested it with online PEG playground

Support escaped $ symbol in snippet body

---

lib/snippet-expansion.coffee
spec/snippets-spec.coffee

Cursors were being already tracked, but only when moving them. When `Esc` gets pressed, cursors are not moved: editor, in facts, consolidates selections, thus destroying some of the cursors. This solves https://github.com/atom/atom/issues/4821
/cc: @izuzak @nathansobo

Terminate snippets when cursor gets destroyed

---

lib/snippet-expansion.coffee
spec/snippets-spec.coffee

After testing, I'm convinced that destruction of `newSelection` does not need to be handled. Handling cursor change should be enough, and it doesn't have the side effect of breaking the tab stops.
Fixes #118

Fix same index tab stops exiting prematurely

---

lib/snippet-body.pegjs
spec/body-parser-spec.coffee

Aim to resolve #60.
To include } in your placeholder content selection, escape it with two \ :
```
it('${1:does something}' ${2:, function($3) {
$4
\\}});
```

Handle escaped characters in tab-stop placeholder content

---

lib/snippet-expansion.coffee

Marker events changed a little in Atom 0.200. This fixes cursor movement handling to work with the new contract. It also simplifies the logic for terminating snippet expansion to match the description in [the existing spec](https://github.com/atom/snippets/blob/master/spec/snippets-spec.coffee#L223):
> *[The snippet expansion is terminated]* when the cursor is moved beyond the bounds of the current tab stop.
Fixes #139

Fix detection of cursor movement within tab-stops

---

lib/snippets.coffee
spec/snippets-spec.coffee

This will help fix the lang html issue. One caveat is that to null out a snippet, you need to have a prefix. This is because the snippets are stored in the config by prefix. 
The spec does a good job explaining the new functionality.
```coffee
describe "when null snippets are present", ->
beforeEach ->
Snippets.add __filename,
'.source.js':
"some snippet":
prefix: "t1"
body: "this is a test"
'.source.js .nope':
"some snippet":
prefix: "t1"
body: null
it "overrides the less-specific defined snippet", ->
snippets = atom.config.get('snippets', scope: ['.source.js'])
expect(snippets['t1']).not.toBe null
snippets = atom.config.get('snippets', scope: ['.source.js .nope.not-today'])
expect(snippets['t1']).toBe null
```
cc @nathansobo @maxbrunsfeld

Accept null snippets

---

lib/snippets.coffee
spec/snippet-loading-spec.coffee

Snippets from packages are currently loaded according to the order returned from `atom.packages.getLoadedPackages()`. However, core packages are always returned at the end of the list, making it impossible for another package to override snippets from a core package like `language-javascript`.
This pr sorts the results from `getLoadedPackages` so that snippets from core packages are loaded before.

Load snippets from core packages first

---

spec/snippet-loading-spec.coffee

The spec shouldn't be dependent on the directory from which the snippets are loaded, since that is different depending on whether one is building Atom from source or installing it. Simply check that the first item is from the `language-javascript` package.
This wasn't failing on the snippets package, but is failing for OS X on Core and when run locally.

:green_heart: Fix load core snippets first spec

---

README.md

I thought adding this to the README would be useful, after reading [issue 162](https://github.com/atom/snippets/issues/162).

Add explanation of how to escape curly brackets.

---

lib/snippets.cson

Hi,
When I'm writing snippets it's really common to create many snippets under one source definition, so I added a snippet for that.
Not sure if snipk/"Atom Snippet Keys" is the best naming for that but it fits.
I also changed the placeholder for prefix because I think it would be easier to understand. Actually there is any reason why the key is not called "trigger" instead of "prefix"? I think it would be much easier to understand, if you guys think it is a good idea I can try to implement it maintaining compatibility, although I think that changing it at this point will probably cause more confusion than benefits.

Add snippet to create snippets under a source definition

---

README.md

readme currently lists that action under Edit, but it's under File on Atom 1.0.13 for Windows

:memo: changing "Open Your Snippets" location to File

---

spec/snippets-spec.coffee

Related to the PR on atom core atom/atom#8604
I have a PR on atom core that changes the behavior of consolidateSelections. That build failed because snippets is using that function to remove cursors in its spec.
This PR just removes the cursor manually in the spec - so as not to rely on consolidateSelections

no longer rely on consolidateSelections to remove cursors in spec

---

README.md

Since all the examples use `source.js`, it's unclear if the JS source type has a period in it or if the period is required for all source keys in your snippets file. This makes it very clear, but maybe I'm the only one that was baffled.

Explicitly mention the period prefix

---

README.md

Before the instructions for Linux were the same as for windows, which did not accurately describe the situation in Linux. I created issue #183 to describe this problem earlier. I searched through the project for other incorrect references of how to open the snippets file, but I couldn't find any. I would be willing to fix other instances of this problem if they exist.

:penguin: Fixed documentation for linux

---

lib/snippets.coffee
package.json
spec/snippet-loading-spec.coffee
spec/snippets-spec.coffee

Our current situation on master looks like the following during startup:
Out of 3s, ~410ms are spent in loading snippets:
Although this doesn't synchronously affect Atom's initialization (i.e. `window.onload`), it has an heavy impact on user experience. Indeed, trying to disable the snippets package results in a more fluid and responsive startup.
The idea with this PR is to avoid doing all the work of parsing snippets upfront and to defer it to the last possible moment. In the past, other packages relied on `atom.config.get` to access loaded snippets: because of configuration being eager by design, we couldn't afford this anymore and we've provided a service instead for other packages to use in order to introduce laziness.
The bad news is that this will be a breaking change, whereas the …

Load snippets lazily

---

README.md
lib/snippet.coffee
lib/snippets.coffee
spec/fixtures/package-with-snippets/snippets/test.cson
spec/snippet-loading-spec.coffee

When working on a snippet I was wondering how other packages formatted the results in the autocomplete list. So I found the `autocomplete-plus` API can accept [more parameters for formatting the results](https://github.com/atom/autocomplete-plus/wiki/Provider-API).
> `leftLabel` (optional): This is shown before the suggestion. Useful for return values.
`leftLabelHTML` (optional): Use this instead of leftLabel if you want to use html for the left label.
`rightLabel` (optional): An indicator (e.g. function, variable) denoting the "kind" of suggestion this represents
`rightLabelHTML` (optional): Use this instead of rightLabel if you want to use html for the right label.
I thought it would be awesome to be able to visually format results for snippets too, so I have added those properties in …

Added more formatting options for snippets

---

README.md

I fixed `path` in the readme for OS X

Fix path in the menu

---

lib/snippet-expansion.coffee
spec/snippets-spec.coffee

Removed some unused variables and improved forward compatibility with coffee-script >=1.9.0
Similar case to atom/autocomplete-plus#768

Remove unused variables and fix references to fields

---

lib/snippets.coffee

Using `openTextFile` just creates an editor without adding it as a pane item, permitting the in-progress `open` call to determine where the item is placed. This ensures options like `{split: ‘left’}` work correctly when opening this URI.

Don’t add pane items in the `atom://.atom/snippets` opener callback

---

lib/helpers.js
lib/snippets.coffee

Add the function `getPackageRoot` and use it to calculate the path to `snippets.{cson,json}`.
I had to manually apply the changes to an Atom clone to test (I want it packaged in asar, snapshotted), by running `script/bootstrap`, copying the changes, and commenting out the bootstrap line in `script/build`. Maybe there is a better way to build Atom with a different private Git copy of a package, but it seems like `packageDependencies` doesn't support Git urls, and there is no obvious way to execute apm to install a Git package into a local Atom Git clone node_modules directory.
Such issues likely repeat them self throughout the builtin Atom packages. Extracting such logic to a shared location and reusing it might help. Note that the exact logic required slightly different from case to case. …

Make the bundled snippets work when the package is snapshotted

---

lib/snippet.coffee
lib/snippets-available.js
lib/snippets.coffee

Basically:
* Remove uses of underscore where it makes sense
* Prevent unnecessary implicit for-loop returns
None.
Slight code cleanup.  Execution should be slightly faster now that we're not shoving all the results from the for loop into an array and returning it.
None.
None.

Very minor cleanup

---

lib/snippet-expansion.coffee
spec/snippets-spec.coffee

Before this PR, this is how snippet expansion worked:
1. The entire snippet body would be inserted into the editor
2. Tab stop markers would be added
3. Tabs would be converted to spaces (and vice versa) if necessary
4. If the snippet consisted of multiple lines, all lines would be indented to match the first line's indentation level
This process worked pretty well, except for one case - when there was a tab stop at the beginning of a subsequent line in a multiline snippet.  In this case, the tab stop marker would initially be placed at `[line, 0], [line, …

Correctly place tab stops when there are multiple indented lines

---

lib/snippets.coffee
spec/snippets-spec.coffee

Before, `loaded` was a global variable.  This meant that once it was set to true it would stay true forever, even after deactivating and reactivating snippets.  This PR changes it to an instance variable so that its state is reset correctly across activations.
None.
This makes the `bundledSnippetsLoaded` method of `provideSnippets()` much more reliable, as previously it would return the wrong value if snippets was deactivated then reactivated.
None.
Refs atom/settings-view#998, in which I have been experimenting with using `bundledSnippetsLoaded`.

Make `loaded` an instance variable

---

lib/snippets.coffee

This PR stops the loading of a snippets file if duplicate keys are encountered.  As duplicate keys are always a mistake, it makes sense to show an error.
Only user snippets should be checked for duplicate keys.  Though if all snippets are checked, it's a good way to "shame" package authors into fixing their snippets file (such as core's language-sass).  The downside is more issues on atom/atom though as people copy/paste the error into a new issue.
Visible error with duplicate keys
See alternate designs above.
Fixes #72

Error when duplicate keys are encountered

---

lib/snippet-expansion.coffee
lib/snippets.coffee
spec/snippets-spec.coffee

Previously, when you hit `tab` inside the last tab stop of a snippet, it would be treated as an ordinary `tab`.
Now, to bring Atom's behavior more in line with Sublime Text, hitting tab within the last tab stop moves the cursor to the end of the tab stop and terminates the snippet expansion. From this point forward, the tab stops will no longer be present and `tab` will function as it normally does.
This PR also moves tab stop markers into their own marker layer so that they can be managed with the history. I had hoped this would enable you to cycle through tab stops after expanding, undoing, and redoing, but there is a bug in restoring markers that will need to be fixed before that will work.
This prevents us from leaking markers and provides a somewhat more intuitive experience for …

When hitting tab within the last tab stop, jump to end of tab stop and terminate the snippet expansion

---

lib/snippets.coffee
spec/snippets-spec.coffee

Fixes https://github.com/atom/atom/issues/16621
Depends on https://github.com/atom/atom/pull/16797

Fallback to reading snippets with legacy scope aliases if available

---

lib/snippet-body.pegjs
spec/body-parser-spec.coffee
spec/snippets-spec.coffee

#266 describes a regression with tab stop behavior when the placeholder contains a reference to another tab stop. This almost certainly happened as a result of #260, but there wasn't any test coverage for this particular usage.
The parser was incorrectly assuming that all the items it would receive for a particular rule would be represented as strings, and that it could thus join them all together. Tabstop references are represented as objects. So I wrote a couple of utility functions to ensure that adjacent strings would be merged together without …

Fix incorrect parsing of placeholders that point to other tab stops.

---

lib/snippet-expansion.coffee
lib/snippets.coffee
spec/snippets-spec.coffee

Fixes https://github.com/atom/atom/issues/17055
This package adds commands to *all* text-editors, but previously, some of its internal state was only maintained for text editors that were added to the workspace as pane items. This PR makes the package work for all text editors, including the commit message editor.

Make snippets work for editors that aren't pane items

---

lib/snippet-expansion.coffee
lib/tab-stop-list.js
spec/snippets-spec.coffee

Fixes #278.
Issue #278 describes the problem: when a snippet contains an explicit `$0`, and when the user cycles through the snippet to that end stop, the next press of <kbd>Tab</kbd> does nothing. This doesn’t have any benefit for the user and behaves differently from other implementations of snippets (Sublime Text, VSCode, etc.).
This behavior was introduced (inadvertently, I think) in #262, whose effect was to add an implied `$0` at the end of every snippet that didn’t have its own `$0`. If I were doing a larger overhaul here, I’d want to refactor so as to remove the need for a `goToEndOfLastTabStop` method altogether. But I think that’d be touching a lot of code just to fix a pretty minor issue, so I went for the simpler fix.
Brings the behavior of snippets more in line with other …

Fix behavior when pressing Tab after a snippet reaches an explicit end stop.

---

spec/snippets-spec.coffee

The `editor.update()` method returns a Promise, which under some circumstances (on specs mostly) never gets resolved.
Because of CoffeeScript's implicit returns, this Promise was returned on the `beforeEach()` method of these tests.
Before https://github.com/atom/atom/pull/18917, any Promise that was returned by a spec method was just discarded, so this behaviour didn't cause any issue, but once we merge that PR this test is going to start failing because jasmine will wait indefinitely until the Promise is resolved.
Figure out why the Promise that gets returned by `editor.update()` never gets resolved. I've started investigating it and this only happens when [this codepath](https://github.com/atom/atom/blob/master/src/text-editor.js#L535) gets executed.
The official tests for `TextEditor` …

Don't return an unresolved Promise on beforeEach()

---

spec/snippets-spec.coffee

Adds tests from #261 for an issue that has been since fixed. I could not find any tests that explicitly test this, which this pull request attempts to remedy. These tests fail pre-1.3.0 release.
#261

Add regression tests for tab stops at ends of snippets

---

lib/insertion.js
lib/snippet-expansion.js
lib/snippet.js
lib/tab-stop.js
spec/snippets-spec.js

_(For whatever reason, I neglected to land #281 before the total decaffeination of this package, which means it's been in limbo for more than two years. This is that same change written in JS rather than CoffeeScript.)_
Fixes #15.
Here’s a simple example of a snippet that has never quite worked right.
```
${2:bar}${3:baz}
```
I’ll quote from my comment in #236 to explain how this goes wrong:
> I’ll use parentheses to illustrate the invisible markers. After tab expansion, you’ve got:
> 
> ```
> (bar)(baz)
> ```
> 
> You type `x` and now you’ve got:
> 
> ```
> (x)(baz)
> ```
> 
> The editor knows to put `x` into the first marker because bar was selected, and that removed all ambiguity. But right now the cursor is between `x` and `baz`, so when you type text, it could plausibly get added to …

Fix behavior when inserting content between two adjacent tab stops
